config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users

  root to: "tasks#index"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  enum status: { backlog: 'backlog', in_progress: 'in_progress', done: 'done' }


  validates :title, :description, :status, :deadline, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = current_user.tasks
  end

  def show
  end

  def new
    @task = current_user.tasks.build
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :status, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="/">Task Management App</a>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"  %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <% if notice %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_editform.html.erb
<%= form_with(model: @task, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.label :status %>
      <%= form.select :status, Task.statuses.keys.map { |status| [status.humanize, status] }, {}, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.label :deadline %>
      <%= form.datetime_select :deadline, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.submit 'Update Task', class: 'btn btn-dark' %>
    </div>
  <% end %>
  

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys.map { |status| [status.humanize, status] }, {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Create Task', class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="jumbotron">
  <div class="row">
    <h3 class="display-4 col"><%= task.title %></h1>
    <% if task.status == "backlog" %>
      <% badge_class = "badge-danger" %>
    <% elsif task.status == "done" %>
      <% badge_class = "badge-success" %>
    <% else %>
      <% badge_class = "badge-warning" %>
    <% end %>
    <span style="float:right; height: 21px; width: 80px;" class="badge badge-pill <%= badge_class %>"><%= task.status %></span>
  </div>
  <h6 class="lead"><%= task.description %></h6>
  <hr class="my-4">
  <p>Due on: <%= task.deadline.to_date %></p>
  <p class="lead">
    <a href="<%= edit_task_path(task) %>" class="btn btn-dark">Edit Task</a>
    <a href="<%= tasks_path %>" class="btn btn-dark">Back to tasks</a>
    <%= button_to "Destroy this task", @task, method: :delete %>
  </p>
</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "editform", task: @task %>

<br>

<div>
  <a href="<%= task_path(@task) %>" class="btn btn-dark">Show this Task</a>
  <a href="<%= tasks_path %>" class="btn btn-dark">Back to tasks</a>
</div>

app/views/tasks/index.html.erb
<a href="<%= new_task_path %>" class="btn btn-dark mb-4">Create a new task</a>
<div class="row">
  <% @tasks.each do |task| %>
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
         <div class="row">
          <h5 class="col card-title"><%= task.title %></h5>
          <% if task.status == "backlog" %>
            <% badge_class = "badge-danger" %>
          <% elsif task.status == "done" %>
            <% badge_class = "badge-success" %>
          <% else %>
            <% badge_class = "badge-warning" %>
          <% end %>
          <span style="float:right; height: 21px; width: 80px;" class="badge badge-pill <%= badge_class %>"><%= task.status %></span>
         </div>
          <p class="card-text"><%= task.description %></p>
          <p class="card-text"><small class="text-muted">Due on: <%= task.deadline.to_date %></small></p>
          <a href="<%= task_path(task) %>" class="btn btn-dark">View Task</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <h1 class="col">New task</h1>
  <a style="float:right; height: 40px;" href="<%= tasks_path %>" class="btn btn-dark">Back to tasks</a>
</div>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<%= render @task %>